#!/usr/bin/env python3
"""Generate compiled action metadata from the canonical action spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "specs" / "actions" / "actions.yaml"
OUTPUT = ROOT / "src" / "api" / "generated_action_metadata.inc"
PURPOSES = {
    "discover", "configure", "query", "inspect", "analyze", "trace",
    "verify", "export", "manage", "transform", "orchestrate",
}


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def cpp_vector(values: list[str]) -> str:
    return "{" + ", ".join(cpp_string(value) for value in values) + "}"


def validate(entry: dict) -> None:
    name = entry["name"]
    for key in ("description_en", "description_zh"):
        if not isinstance(entry.get(key), str) or not entry[key].strip():
            raise ValueError(f"{name}: missing {key}")
    for key in ("purposes", "use_for", "do_not_use_for"):
        value = entry.get(key)
        if not isinstance(value, list) or not value or not all(
            isinstance(item, str) and item.strip() for item in value
        ):
            raise ValueError(f"{name}: {key} must be a non-empty string array")
    unknown = set(entry["purposes"]) - PURPOSES
    if unknown:
        raise ValueError(f"{name}: unsupported purposes {sorted(unknown)}")
    if not isinstance(entry.get("preferred_alternative"), dict):
        raise ValueError(f"{name}: preferred_alternative must be an object")


def render() -> str:
    entries = json.loads(SPEC.read_text(encoding="utf-8"))["actions"]
    lines = ["// Generated by tools/sync_action_metadata.py. Do not edit."]
    for entry in entries:
        if entry.get("status") == "removed":
            continue
        validate(entry)
        lines.extend([
            f"if (spec.name == {cpp_string(entry['name'])}) {{",
            f"    spec.description_en = {cpp_string(entry['description_en'])};",
            f"    spec.description_zh = {cpp_string(entry['description_zh'])};",
            f"    spec.purposes = {cpp_vector(entry['purposes'])};",
            f"    spec.use_for = {cpp_vector(entry['use_for'])};",
            f"    spec.do_not_use_for = {cpp_vector(entry['do_not_use_for'])};",
            "    spec.preferred_alternative = Json::object();",
        ])
        for key, value in entry["preferred_alternative"].items():
            lines.append(
                f"    spec.preferred_alternative[{cpp_string(key)}] = {cpp_string(value)};"
            )
        lines.extend(["    return;", "}"])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated action metadata: {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
